In [6]:
import pandas as pd

In [7]:
championship23_24 = pd.read_csv('https://football-data.co.uk/mmz4281/2324/E1.csv')

In [8]:
championship23_24

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E1,04/08/2023,20:00,Sheffield Weds,Southampton,1,2,A,0,1,...,1.83,0.25,1.91,1.99,1.93,2.00,1.97,2.00,1.88,1.95
1,E1,05/08/2023,15:00,Blackburn,West Brom,2,1,H,2,0,...,1.70,0.00,2.05,1.85,2.07,1.85,2.10,1.88,2.03,1.82
2,E1,05/08/2023,15:00,Bristol City,Preston,1,1,D,0,0,...,1.68,-0.25,1.82,2.08,1.84,2.08,1.88,2.15,1.80,2.04
3,E1,05/08/2023,15:00,Middlesbrough,Millwall,0,1,A,0,0,...,1.77,-0.25,1.80,2.10,1.83,2.10,1.91,2.14,1.85,1.99
4,E1,05/08/2023,15:00,Norwich,Hull,2,1,H,1,1,...,1.92,-0.75,2.06,1.84,2.05,1.86,2.10,1.91,2.01,1.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,E1,22/01/2024,20:00,Leicester,Ipswich,1,1,D,1,0,...,1.98,-0.75,2.07,1.83,2.06,1.86,2.09,1.88,2.03,1.81
336,E1,24/01/2024,19:45,Leeds,Norwich,1,0,H,1,0,...,2.67,-1.50,2.04,1.86,2.07,1.85,2.08,1.90,2.02,1.83
337,E1,27/01/2024,15:00,Millwall,Preston,1,1,D,1,1,...,1.52,-0.25,1.88,2.02,1.88,2.02,1.89,2.15,1.82,2.03
338,E1,27/01/2024,15:00,Sunderland,Stoke,3,1,H,1,0,...,1.82,-0.50,2.05,1.85,2.05,1.86,2.06,1.88,2.00,1.84
339,E1,28/01/2024,13:30,QPR,Huddersfield,1,1,D,0,0,...,1.64,-0.50,1.95,1.95,1.95,1.95,2.00,2.00,1.95,1.90

In [9]:
championship23_24.rename(columns={'FTHG':'home_goals',
                                  'FTAG':'away_goals'}, inplace=True)

In [10]:
championship23_24

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E1,04/08/2023,20:00,Sheffield Weds,Southampton,1,2,A,0,1,...,1.83,0.25,1.91,1.99,1.93,2.00,1.97,2.00,1.88,1.95
1,E1,05/08/2023,15:00,Blackburn,West Brom,2,1,H,2,0,...,1.70,0.00,2.05,1.85,2.07,1.85,2.10,1.88,2.03,1.82
2,E1,05/08/2023,15:00,Bristol City,Preston,1,1,D,0,0,...,1.68,-0.25,1.82,2.08,1.84,2.08,1.88,2.15,1.80,2.04
3,E1,05/08/2023,15:00,Middlesbrough,Millwall,0,1,A,0,0,...,1.77,-0.25,1.80,2.10,1.83,2.10,1.91,2.14,1.85,1.99
4,E1,05/08/2023,15:00,Norwich,Hull,2,1,H,1,1,...,1.92,-0.75,2.06,1.84,2.05,1.86,2.10,1.91,2.01,1.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,E1,22/01/2024,20:00,Leicester,Ipswich,1,1,D,1,0,...,1.98,-0.75,2.07,1.83,2.06,1.86,2.09,1.88,2.03,1.81
336,E1,24/01/2024,19:45,Leeds,Norwich,1,0,H,1,0,...,2.67,-1.50,2.04,1.86,2.07,1.85,2.08,1.90,2.02,1.83
337,E1,27/01/2024,15:00,Millwall,Preston,1,1,D,1,1,...,1.52,-0.25,1.88,2.02,1.88,2.02,1.89,2.15,1.82,2.03
338,E1,27/01/2024,15:00,Sunderland,Stoke,3,1,H,1,0,...,1.82,-0.50,2.05,1.85,2.05,1.86,2.06,1.88,2.00,1.84
339,E1,28/01/2024,13:30,QPR,Huddersfield,1,1,D,0,0,...,1.64,-0.50,1.95,1.95,1.95,1.95,2.00,2.00,1.95,1.90